import { Navbar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import { NavProvider } from '@/context'

const raleway = Raleway({
  weight: ['100', '400', '700'],
  subsets: ['latin'],
  variable: '--font-Raleway',
  display: 'block'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <NavProvider>
          <Navbar />
          {children}
        </NavProvider>
      </body>
    </html>
  )
}
